/**
 Copyright (C) 2022.
 Licensed under the  GPL-3.0 License;
 You may not use this file except in compliance with the License.
 It is supplied in the hope that it may be useful.
 * @project_name : Ikratos-MD-v1
 * @author : xIKRATOSx <https://github.com/xIKRATOSx>
 * @description : Ikratos-MD-v1,A Multi-functional simple and light weight whatsapp bot.
 * @version 1.0.0
 * @file : index.js
 **/


import { fancy, randomfancy } from './scrape.js'
import {
    listall,
    strikeThrough,
    wingdings,
    vaporwave,
    typewriter,
    analucia,
    tildeStrikeThrough,
    underline,
    doubleUnderline,
    slashThrough,
    sparrow,
    heartsBetween,
    arrowBelow,
    crossAboveBelow,
    creepify,
    bubbles,
    mirror,
    squares,
    roundsquares,
    flip,
    tiny,
    createMap,
    serif_I,
    manga,
    ladybug,
    runes,
    serif_B,
    serif_BI,
    fancy1,
    fancy2,
    fancy3,
    fancy4,
    fancy5,
    fancy6,
    fancy7,
    fancy8,
    fancy9,
    fancy10,
    fancy11,
    fancy12,
    fancy13,
    fancy14,
    fancy15,
    fancy16,
    fancy17,
    fancy18,
    fancy19,
    fancy20,
    fancy21,
    fancy22,
    fancy23,
    fancy24,
    fancy25,
    fancy26,
    fancy27,
    fancy28,
    fancy29,
    fancy30,
    fancy31,
    fancy32,
    fancy33,
    randomStyle
} from './stylish-font.js'
export default {
    fancy,
    randomfancy,
    listall,
    strikeThrough,
    wingdings,
    vaporwave,
    typewriter,
    analucia,
    tildeStrikeThrough,
    underline,
    doubleUnderline,
    slashThrough,
    sparrow,
    heartsBetween,
    arrowBelow,
    crossAboveBelow,
    creepify,
    bubbles,
    mirror,
    squares,
    roundsquares,
    flip,
    tiny,
    createMap,
    serif_I,
    manga,
    ladybug,
    runes,
    serif_B,
    serif_BI,
    serif_I,
    fancy1,
    fancy2,
    fancy3,
    fancy4,
    fancy5,
    fancy6,
    fancy7,
    fancy8,
    fancy9,
    fancy10,
    fancy11,
    fancy12,
    fancy13,
    fancy14,
    fancy15,
    fancy16,
    fancy17,
    fancy18,
    fancy19,
    fancy20,
    fancy21,
    fancy22,
    fancy23,
    fancy24,
    fancy25,
    fancy26,
    fancy27,
    fancy28,
    fancy29,
    fancy30,
    fancy31,
    fancy32,
    fancy33,
    randomStyle,
    fancytext: (text, index) => {
        index = index - 1;
        return listall(text)[index];
    },
    
    isNumber: function isNumber() {
        const int = parseInt(this);
        return typeof int === "number" && !isNaN(int);
    },
    
}